# Generated by Django 4.2.1 on 2023-05-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApi', '0002_company_device_employee_deviceassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceassignment',
            name='condition_when_checked_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceassingments', to='TrackApi.device'),
        ),
    ]
