# Generated by Django 4.2.1 on 2023-05-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApi', '0003_alter_deviceassignment_condition_when_checked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackApi.employee'),
        ),
    ]
