# Generated by Django 4.2.1 on 2023-05-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApi', '0005_phonecompany_alter_deviceassignment_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceassignment',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='device_assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='TrackApi.deviceassignment'),
            preserve_default=False,
        ),
    ]
