# Generated by Django 4.2.1 on 2023-05-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApi', '0007_deviceusagelist_rename_phonecompany_devicebrand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_usage', to='TrackApi.devicelog')),
                ('phone_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackApi.devicebrand')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceUsageList',
        ),
    ]
