# Generated by Django 4.2.1 on 2023-05-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApi', '0008_deviceusage_delete_deviceusagelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelog',
            old_name='condition_when_checked_out',
            new_name='condition_when_handed_over',
        ),
        migrations.RenameField(
            model_name='devicelog',
            old_name='condition_when_checked_in',
            new_name='condition_when_returned',
        ),
        migrations.RenameField(
            model_name='devicelog',
            old_name='check_out_date',
            new_name='hand_over_date',
        ),
        migrations.RenameField(
            model_name='devicelog',
            old_name='check_in_date',
            new_name='return_date',
        ),
    ]
