# Generated by Django 4.2.1 on 2023-05-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackApi', '0009_rename_condition_when_checked_out_devicelog_condition_when_handed_over_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceBrand',
            new_name='DeviceCompany',
        ),
        migrations.RenameField(
            model_name='deviceusage',
            old_name='phone_company',
            new_name='device_company',
        ),
    ]
